---
- name: configure nginx 
  hosts: webservers
  tasks: 
  - name: install nginx webserver
    yum: 
      name: nginx
      state: latest
  - name: start nginx webserver
    service:
      name: nginx
      state: started