---
- name: configure nginx 
  hosts: webservers
  tasks: 
  - name: stop nginx webserver
    service:
      name: nginx
      state: stopped
  - name: uninstall nginx webserver
    yum: 
      name: nginx
      state: absent
  